/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OOP_WORDLE;

import javax.swing.UIDefaults.ProxyLazyValue;

public class App {
	
	static void ciao() {
		System.out.println("Ciao");
	}
    
    static void prova() {
        System.out.println("prova git");
    }

    public static void main(String[] args) {
    	System.out.println("Hello World!");
    	System.out.println("Hello World!");
    	ciao();

    	doNothing("Ciao");
    }
    
    private static void doNothing(String arg) {
    	System.out.println("Ciao" + " " + arg);
    	prova();
    }
}
