/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package OOP_WORDLE;

public class App {

    public static void main(String[] args) {
    	System.out.println("Hello World!");
    	System.out.println("Hello World!");
    	doNothing("Ciao");
    }
    
    private static void doNothing(String arg) {
    	System.out.println("Ciao" + " " + arg);
    }
}
